version: "3.9"
services:
  web_server:
    build: .
    container_name: django_container
    ports:
      - "8000:8000"
    restart: always
    links:
      - db_postgres
      - redis_db
    depends_on:
      - db_postgres
      - redis_db
  db_postgres:
    build: ./database
    environment:
      - POSTGRES_DB=$POSTGRES_NAME
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASS
    container_name: db_container
    volumes:
      - ./database:/app/database
    ports:
      - "5432:5432"
    restart: always
  redis_db:
    image: "redis:alpine"
    container_name: redis_container
    ports:
      - "6379:6379"
    restart: always
  nginx:
    build: ./nginx
    volumes:
      - static:/app/project_dir/static
    ports:
      - "80:80"
    depends_on:
      - web_server


