version: "3.9"
services:
  web_server:
    build: .
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ./project_dir/static:/static
    links:
      - db_postgres
      - redis_db
    depends_on:
      - db_postgres
      - redis_db
  db_postgres:
    build: ./database
    environment:
      - POSTGRES_DB=$POSTGRES_NAME
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASS
    volumes:
      - ./database:/app/database
    ports:
      - "5432:5432"
    restart: always
  redis_db:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    restart: always
  nginx:
    build: ./nginx
    volumes:
      - ./project_dir/static:/app/static
      - ./nginx/default.conf:/app/nginx/default.conf
    ports:
      - "80:80"
    depends_on:
      - web_server
    links:
      - web_server



