# Generated by Django 4.0.4 on 2022-06-06 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request_JSONB_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Recorded Time')),
                ('payload', models.JSONField(null=True, verbose_name='Payload')),
            ],
        ),
    ]
