# Generated by Django 4.0.4 on 2022-06-02 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request_JSONB',
            new_name='Request_JSONB_Model',
        ),
    ]
