# Generated by Django 4.0.4 on 2022-06-02 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outer', '0003_alter_request_jsonb_model_request_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request_jsonb_model',
            name='request_set',
        ),
        migrations.AddField(
            model_name='request_jsonb_model',
            name='answer',
            field=models.JSONField(null=True, verbose_name='answer'),
        ),
        migrations.AddField(
            model_name='request_jsonb_model',
            name='clues_count',
            field=models.JSONField(null=True, verbose_name='clues_count'),
        ),
        migrations.AddField(
            model_name='request_jsonb_model',
            name='created_at',
            field=models.JSONField(null=True, verbose_name='created_at'),
        ),
        migrations.AddField(
            model_name='request_jsonb_model',
            name='question',
            field=models.JSONField(null=True, verbose_name='question'),
        ),
        migrations.AddField(
            model_name='request_jsonb_model',
            name='value',
            field=models.JSONField(null=True, verbose_name='value'),
        ),
    ]
