# Generated by Django 4.0.4 on 2022-06-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outer', '0004_remove_request_jsonb_model_request_set_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request_jsonb_model',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='request_jsonb_model',
            name='clues_count',
        ),
        migrations.RemoveField(
            model_name='request_jsonb_model',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='request_jsonb_model',
            name='question',
        ),
        migrations.RemoveField(
            model_name='request_jsonb_model',
            name='value',
        ),
        migrations.AddField(
            model_name='request_jsonb_model',
            name='payload',
            field=models.JSONField(null=True, verbose_name='Payload'),
        ),
    ]
