# Generated by Django 4.0.4 on 2022-05-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='rating',
            field=models.IntegerField(null=True, verbose_name='Rating Of publication'),
        ),
    ]
