# Generated by Django 4.0.4 on 2022-05-28 15:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='user',
        ),
        migrations.RemoveField(
            model_name='person',
            name='user',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.person', verbose_name='Bookmark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='person',
            name='password',
            field=models.TextField(null=True, verbose_name='Password'),
        ),
        migrations.AddField(
            model_name='person',
            name='username',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Username'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.person', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='req_count',
            field=models.IntegerField(null=True, verbose_name='Counter watched times'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(null=True, verbose_name='Title of Article'),
        ),
    ]
