# Generated by Django 4.0.4 on 2022-05-27 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Bookmark')),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='email',
        ),
        migrations.RemoveField(
            model_name='person',
            name='login',
        ),
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='token',
            field=models.TextField(max_length=555, verbose_name='JWT'),
        ),
        migrations.AlterField(
            model_name='person',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='post',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.person', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=3000, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='post',
            name='discription',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='post',
            name='disslike',
            field=models.IntegerField(null=True, verbose_name='Disslike'),
        ),
        migrations.AlterField(
            model_name='post',
            name='like',
            field=models.IntegerField(null=True, verbose_name='Like'),
        ),
        migrations.AlterField(
            model_name='post',
            name='req_count',
            field=models.IntegerField(null=True, verbose_name='Counter'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slag_field',
            field=models.CharField(max_length=1000, verbose_name='Slag'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(null=True, verbose_name='Title'),
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bookmark', verbose_name='link_bookmark')),
                ('posts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='bookmarks',
            field=models.ManyToManyField(through='app.Link', to='app.bookmark'),
        ),
    ]
