# Generated by Django 4.0.4 on 2022-06-05 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['user'], 'verbose_name': 'Registred User', 'verbose_name_plural': "Registred User's"},
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='person',
        ),
        migrations.RemoveField(
            model_name='link',
            name='posts',
        ),
        migrations.RemoveField(
            model_name='person',
            name='email',
        ),
        migrations.RemoveField(
            model_name='person',
            name='password',
        ),
        migrations.RemoveField(
            model_name='person',
            name='username',
        ),
        migrations.RemoveField(
            model_name='post',
            name='bookmarks',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='posts',
            field=models.ManyToManyField(to='app.post', verbose_name='Subscribed posts'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='person', to='app.person', verbose_name='Bookmark'),
        ),
        migrations.AddField(
            model_name='link',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.post'),
        ),
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='link',
            name='bookmark',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.bookmark'),
        ),
    ]
