# Generated by Django 4.0.4 on 2022-06-14 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_link_whos_link_alter_link_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.post', verbose_name='Which_post'),
        ),
    ]
