# Generated by Django 4.0.4 on 2022-05-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_bookmark_user_remove_person_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='username',
            field=models.TextField(max_length=100, verbose_name='Username'),
        ),
    ]
