# Generated by Django 4.0.4 on 2022-06-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_person_token_person_additional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='disslike',
        ),
        migrations.RemoveField(
            model_name='post',
            name='like',
        ),
        migrations.AddField(
            model_name='link',
            name='disslike',
            field=models.IntegerField(null=True, verbose_name='Disslike'),
        ),
        migrations.AddField(
            model_name='link',
            name='like',
            field=models.IntegerField(null=True, verbose_name='Like'),
        ),
    ]
