# Generated by Django 4.0.4 on 2022-06-05 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_post_disslike_remove_post_like_link_disslike_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='disslike',
            field=models.BooleanField(default=False, verbose_name='Disslike'),
        ),
        migrations.AlterField(
            model_name='link',
            name='like',
            field=models.BooleanField(default=False, verbose_name='Like'),
        ),
    ]
